Dev 44 accept reject book collab
Authorie/authorie pull request #90
Opened 2023-04-07 20:44 UTC by Four58

2023-04-07 20:49 UTC, Four58 reviewed
fix ui bugs such as: view archive only available for owner, create page is valid for login user, authorbanner upload pic, usercard create clickable, add logic to show book on book page, add accept reject collab

2023-04-08 12:00 UTC, Four58 reviewed
good to go!

2023-04-08 12:13 UTC, swsd2544 requested changes

2023-04-08 12:13 UTC, swsd2544 commented on src/components/Book/Book.tsx
> +  });
use either onSuccess or onSettled. This only invalidates the book cache (all book API), perhaps making the website slower. Maybe we need to invalidate the getCollaborationInvite API too. Please recheck this.

2023-04-08 14:32 UTC, swsd2544 requested changes

2023-04-08 14:32 UTC, swsd2544 commented on src/components/Book/Book.tsx
> +  ownerPenname: string | null;
```suggestion
  ownerPenname: string;
```

2023-04-08 14:32 UTC, swsd2544 commented on src/components/Book/Book.tsx
> +      void utils.user.getBookCollaborators.invalidate();
```suggestion
      void Promise.all([utils.book.invalidate(),
      utils.user.getBookCollaborators.invalidate()]);
```

2023-04-08 14:35 UTC, swsd2544 commented on src/components/Book/BookList.tsx
> +      )}
extract this to a new function, use book.map like this will have some undefined in the array --> use filter before map

2023-04-08 16:26 UTC, swsd2544 approved these changes

2023-04-08 16:26 UTC, merged